/**
 * Notification Constants
 *
 * Shared constants for the notification system.
 * This file can be safely imported in both client and server code.
 *
 * Based on VerifAI UAT email templates - 73 English templates organized by category.
 */

// ==================== NOTIFICATION CHANNELS ====================
export const NOTIFICATION_CHANNELS = {
  INBOX: 'inbox',
  EMAIL: 'email',
} as const;

export type NotificationChannel = (typeof NOTIFICATION_CHANNELS)[keyof typeof NOTIFICATION_CHANNELS];

// ==================== NOTIFICATION EVENTS ====================
export const NOTIFICATION_EVENTS = {
  // ===================== INTERNAL AUDIT =====================
  AUDIT_CREATED: 'AUDIT_CREATED',
  FINDINGS_CREATED: 'FINDINGS_CREATED',
  FINDINGS_COMPLETED: 'FINDINGS_COMPLETED',
  AUDIT_PLAN_CREATED: 'AUDIT_PLAN_CREATED',
  AUDIT_PLAN_SCHEDULED: 'AUDIT_PLAN_SCHEDULED',
  AUDIT_PLAN_APPROVAL: 'AUDIT_PLAN_APPROVAL',
  AUDIT_PLAN_ACKNOWLEDGED: 'AUDIT_PLAN_ACKNOWLEDGED',
  AUDIT_PLAN_ACKNOWLEDGEMENT_REMINDER: 'AUDIT_PLAN_ACKNOWLEDGEMENT_REMINDER',
  WORKPAPER_SUBMITTED: 'WORKPAPER_SUBMITTED',
  PROCEDURE_ASSIGNED: 'PROCEDURE_ASSIGNED',
  QUESTION_DELEGATED: 'QUESTION_DELEGATED',
  QUESTION_CLARIFICATION: 'QUESTION_CLARIFICATION',
  CONCLUDE_TEST: 'CONCLUDE_TEST',
  RESPONSE_SUBMITTED: 'RESPONSE_SUBMITTED',
  INTERVIEW_SCHEDULED: 'INTERVIEW_SCHEDULED',
  INTERVIEW_RESCHEDULED: 'INTERVIEW_RESCHEDULED',
  PERIODICITY_INITIATED: 'PERIODICITY_INITIATED',
  REPORT_PUBLISHED: 'REPORT_PUBLISHED',
  REPORT_INITIATED: 'REPORT_INITIATED',
  REPORT_SUBMISSION: 'REPORT_SUBMISSION',
  FIELDWORK_RESPONSE: 'FIELDWORK_RESPONSE',
  FIELDWORK_RESPONSE_REMINDER: 'FIELDWORK_RESPONSE_REMINDER',

  // ===================== EVIDENCE MANAGEMENT =====================
  EVIDENCE_ASSIGNED: 'EVIDENCE_ASSIGNED',
  EVIDENCE_SUBMITTED: 'EVIDENCE_SUBMITTED',
  EVIDENCE_PUBLISHED: 'EVIDENCE_PUBLISHED',

  // ===================== GOVERNANCE & POLICY =====================
  GOVERNANCE_APPROVED: 'GOVERNANCE_APPROVED',
  GOVERNANCE_ASSIGNED: 'GOVERNANCE_ASSIGNED',
  GOVERNANCE_PUBLISHED: 'GOVERNANCE_PUBLISHED',
  GOVERNANCE_SUBMIT_FOR_APPROVAL: 'GOVERNANCE_SUBMIT_FOR_APPROVAL',
  GOVERNANCE_APPROVER: 'GOVERNANCE_APPROVER',
  RESEND_POLICY: 'RESEND_POLICY',

  // ===================== PROCESS MANAGEMENT =====================
  PROCESS_CREATED: 'PROCESS_CREATED',
  PROCESS_ASSIGNED: 'PROCESS_ASSIGNED',
  PROCESS_SUBMIT_FOR_APPROVAL: 'PROCESS_SUBMIT_FOR_APPROVAL',
  PROCESS_APPROVED: 'PROCESS_APPROVED',
  PROCESS_REJECTION: 'PROCESS_REJECTION',

  // ===================== RISK MANAGEMENT =====================
  RISK_CREATED: 'RISK_CREATED',
  RISK_ASSIGNED: 'RISK_ASSIGNED',
  RISK_APPROVED: 'RISK_APPROVED',
  RISK_SUBMIT_FOR_APPROVAL: 'RISK_SUBMIT_FOR_APPROVAL',
  RISK_REJECTION: 'RISK_REJECTION',

  // ===================== CONTROL MANAGEMENT =====================
  CONTROL_ASSIGNED: 'CONTROL_ASSIGNED',
  CONTROL_COMPLIANT: 'CONTROL_COMPLIANT',
  ASSESSMENT_COMPLETED: 'ASSESSMENT_COMPLETED',

  // ===================== ASSET MANAGEMENT =====================
  ASSET_ASSIGNED: 'ASSET_ASSIGNED',

  // ===================== EXCEPTION MANAGEMENT =====================
  EXCEPTION_ASSIGNED: 'EXCEPTION_ASSIGNED',
  EXCEPTION_AUTHORIZED: 'EXCEPTION_AUTHORIZED',
  EXCEPTION_AUTHORIZATION_REQUIRED: 'EXCEPTION_AUTHORIZATION_REQUIRED',
  EXCEPTION_APPROVED: 'EXCEPTION_APPROVED',
  EXCEPTION_DENIED: 'EXCEPTION_DENIED',
  EXCEPTION_SENT_BACK: 'EXCEPTION_SENT_BACK',
  EXCEPTION_CLOSURE: 'EXCEPTION_CLOSURE',
  EXCEPTION_CLOSED: 'EXCEPTION_CLOSED',

  // ===================== ISSUE/FINDING TRACKING =====================
  ISSUE_CREATED: 'ISSUE_CREATED',
  ISSUE_RESOLVED: 'ISSUE_RESOLVED',
  ISSUE_SUBMIT_FOR_CLOSURE: 'ISSUE_SUBMIT_FOR_CLOSURE',
  ISSUE_REJECTED: 'ISSUE_REJECTED',
  ISSUE_RESOLUTION_REMINDER: 'ISSUE_RESOLUTION_REMINDER',
  ISSUE_ESCALATED: 'ISSUE_ESCALATED',
  ISSUE_EVIDENCE: 'ISSUE_EVIDENCE',

  // ===================== PLANNED ACTIONS =====================
  PLANNED_ACTION_RAISE: 'PLANNED_ACTION_RAISE',
  PLANNED_ACTION_REJECTION: 'PLANNED_ACTION_REJECTION',
  PLANNED_ACTION_SUBMIT_FOR_APPROVAL: 'PLANNED_ACTION_SUBMIT_FOR_APPROVAL',
  PLANNED_ACTION_APPROVED: 'PLANNED_ACTION_APPROVED',

  // ===================== KPI =====================
  KPI_UPDATED: 'KPI_UPDATED',
  KPI_SCORE_UPDATED: 'KPI_SCORE_UPDATED',

  // ===================== USER & SYSTEM =====================
  USER_CREATED: 'USER_CREATED',
  CUSTOMER_ONBOARDED: 'CUSTOMER_ONBOARDED',
  SYSTEM_ANNOUNCEMENT: 'SYSTEM_ANNOUNCEMENT',

  // ===================== ENGAGEMENT =====================
  ENGAGEMENT_ASSIGNED: 'ENGAGEMENT_ASSIGNED',

  // ===================== CAPA =====================
  CAPA_ASSIGNED: 'CAPA_ASSIGNED',

  // ===================== POLICY =====================
  POLICY_ASSIGNED: 'POLICY_ASSIGNED',

  // ===================== WORKFLOW EVENTS =====================
  COMMENT_ADDED: 'COMMENT_ADDED',
  APPROVAL_REQUESTED: 'APPROVAL_REQUESTED',
  APPROVAL_GRANTED: 'APPROVAL_GRANTED',
  APPROVAL_DENIED: 'APPROVAL_DENIED',
  SENT_BACK: 'SENT_BACK',
  FEEDBACK_REQUESTED: 'FEEDBACK_REQUESTED',
  STATUS_CHANGED: 'STATUS_CHANGED',

  // ===================== REMINDERS =====================
  EVIDENCE_DUE_REMINDER: 'EVIDENCE_DUE_REMINDER',
  CAPA_DUE_REMINDER: 'CAPA_DUE_REMINDER',
  REVIEW_DUE_REMINDER: 'REVIEW_DUE_REMINDER',
  CLARIFICATION_REMINDER: 'CLARIFICATION_REMINDER',

  // ===================== ESCALATIONS =====================
  ESCALATE_FIELDWORK_RESPONSE: 'ESCALATE_FIELDWORK_RESPONSE',
  ESCALATE_CLARIFICATION: 'ESCALATE_CLARIFICATION',
  ESCALATE_ACKNOWLEDGMENT: 'ESCALATE_ACKNOWLEDGMENT',

  // ===================== TPRM (Third-Party Risk Management) =====================
  TPRM_ACCOUNT_CREATED: 'TPRM_ACCOUNT_CREATED',
  TPRM_VENDOR_ONBOARDED: 'TPRM_VENDOR_ONBOARDED',
  TPRM_VENDOR_OFFBOARDING: 'TPRM_VENDOR_OFFBOARDING',
  TPRM_VENDOR_TERMINATED: 'TPRM_VENDOR_TERMINATED',
  TPRM_ASSESSMENT_INITIATED: 'TPRM_ASSESSMENT_INITIATED',
  TPRM_ASSESSMENT_ASSIGNED: 'TPRM_ASSESSMENT_ASSIGNED',
  TPRM_ASSESSMENT_SUBMITTED: 'TPRM_ASSESSMENT_SUBMITTED',
  TPRM_ASSESSMENT_COMPLETED: 'TPRM_ASSESSMENT_COMPLETED',
  TPRM_ASSESSMENT_RETURNED: 'TPRM_ASSESSMENT_RETURNED',
  TPRM_ASSESSMENT_REASSIGNED: 'TPRM_ASSESSMENT_REASSIGNED',
  TPRM_SME_ASSIGNED: 'TPRM_SME_ASSIGNED',
  TPRM_CLARIFICATION_REQUESTED: 'TPRM_CLARIFICATION_REQUESTED',
  TPRM_COMMENT_ADDED: 'TPRM_COMMENT_ADDED',
  TPRM_OVERRIDE_APPLIED: 'TPRM_OVERRIDE_APPLIED',
  TPRM_VENDOR_ISSUE_CREATED: 'TPRM_VENDOR_ISSUE_CREATED',
  TPRM_SUPPORT_REQUEST: 'TPRM_SUPPORT_REQUEST',
  TPRM_CONTRACT_EXPIRY: 'TPRM_CONTRACT_EXPIRY',
  TPRM_RM_ACCOUNT_CREATED: 'TPRM_RM_ACCOUNT_CREATED',

  // TPRM Assessment Approval
  TPRM_ASSESSMENT_SENT_TO_APPROVER: 'TPRM_ASSESSMENT_SENT_TO_APPROVER',
  TPRM_ASSESSMENT_APPROVED: 'TPRM_ASSESSMENT_APPROVED',

  // TPRM Remediation Workflow
  TPRM_REMEDIATION_CREATED: 'TPRM_REMEDIATION_CREATED',
  TPRM_REMEDIATION_SUBMITTED: 'TPRM_REMEDIATION_SUBMITTED',
  TPRM_REMEDIATION_SATISFIED: 'TPRM_REMEDIATION_SATISFIED',
  TPRM_REMEDIATION_UNSATISFIED: 'TPRM_REMEDIATION_UNSATISFIED',
  TPRM_REMEDIATION_SENT_TO_BUSINESS: 'TPRM_REMEDIATION_SENT_TO_BUSINESS',
  TPRM_REMEDIATION_ASSIGNED_TO_IT: 'TPRM_REMEDIATION_ASSIGNED_TO_IT',
  TPRM_REMEDIATION_IT_SUBMITTED: 'TPRM_REMEDIATION_IT_SUBMITTED',
  TPRM_REMEDIATION_IT_APPROVED: 'TPRM_REMEDIATION_IT_APPROVED',
  TPRM_REMEDIATION_IT_RETURNED: 'TPRM_REMEDIATION_IT_RETURNED',

  // TPRM Vendor Issues
  TPRM_VENDOR_ISSUE_UPDATED: 'TPRM_VENDOR_ISSUE_UPDATED',
  TPRM_VENDOR_ISSUE_RESOLVED: 'TPRM_VENDOR_ISSUE_RESOLVED',

  // TPRM Offboarding Workflow
  TPRM_OFFBOARD_SUBMITTED: 'TPRM_OFFBOARD_SUBMITTED',
  TPRM_OFFBOARD_ASSESSOR_APPROVED: 'TPRM_OFFBOARD_ASSESSOR_APPROVED',
  TPRM_OFFBOARD_ASSESSOR_SENT_BACK: 'TPRM_OFFBOARD_ASSESSOR_SENT_BACK',
  TPRM_OFFBOARD_RM_APPROVED: 'TPRM_OFFBOARD_RM_APPROVED',
  TPRM_OFFBOARD_RM_SENT_BACK: 'TPRM_OFFBOARD_RM_SENT_BACK',
  TPRM_OFFBOARD_BO_APPROVED: 'TPRM_OFFBOARD_BO_APPROVED',
  TPRM_OFFBOARD_BO_SENT_TO_RM: 'TPRM_OFFBOARD_BO_SENT_TO_RM',

  // TPRM Monitoring
  TPRM_MONITORING_SCAN_COMPLETED: 'TPRM_MONITORING_SCAN_COMPLETED',
  TPRM_MONITORING_CRITICAL_RISK: 'TPRM_MONITORING_CRITICAL_RISK',

  // TPRM Clarification Response
  TPRM_CLARIFICATION_RESPONDED: 'TPRM_CLARIFICATION_RESPONDED',

  // TPRM Remediation Lifecycle
  TPRM_REMEDIATION_OVERDUE: 'TPRM_REMEDIATION_OVERDUE',
  TPRM_REMEDIATION_ALL_CLOSED: 'TPRM_REMEDIATION_ALL_CLOSED',

  // TPRM Vendor Issue Escalation
  TPRM_VENDOR_ISSUE_ESCALATED: 'TPRM_VENDOR_ISSUE_ESCALATED',

  // TPRM Scheduled Reminders
  TPRM_ASSESSMENT_DUE_REMINDER: 'TPRM_ASSESSMENT_DUE_REMINDER',
  TPRM_SME_ASSIGNMENT_PENDING: 'TPRM_SME_ASSIGNMENT_PENDING',

  // TPRM Contract Deletion
  TPRM_CONTRACT_DELETION_REQUESTED: 'TPRM_CONTRACT_DELETION_REQUESTED',
  TPRM_CONTRACT_DELETION_APPROVED: 'TPRM_CONTRACT_DELETION_APPROVED',
  TPRM_CONTRACT_DELETION_REJECTED: 'TPRM_CONTRACT_DELETION_REJECTED',
  TPRM_CONTRACT_DELETED_BY_ADMIN: 'TPRM_CONTRACT_DELETED_BY_ADMIN',
} as const;

export type NotificationEvent = (typeof NOTIFICATION_EVENTS)[keyof typeof NOTIFICATION_EVENTS];

// ==================== NOTIFICATION PRIORITIES ====================
export const NOTIFICATION_PRIORITIES = {
  LOW: 'low',
  NORMAL: 'normal',
  HIGH: 'high',
  URGENT: 'urgent',
} as const;

export type NotificationPriority = (typeof NOTIFICATION_PRIORITIES)[keyof typeof NOTIFICATION_PRIORITIES];
