// Dropdown data for Regulatory Intelligence Hub - Organisation Profile

export const COUNTRIES = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia",
  "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus",
  "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil",
  "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada",
  "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo (DRC)",
  "Congo (Republic)", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti",
  "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea",
  "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia",
  "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti",
  "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy",
  "Ivory Coast", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kosovo", "Kuwait",
  "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania",
  "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands",
  "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro",
  "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand",
  "Nicaragua", "Niger", "Nigeria", "North Korea", "North Macedonia", "Norway", "Oman", "Pakistan",
  "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland",
  "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia",
  "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia",
  "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia",
  "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka",
  "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand",
  "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu",
  "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan",
  "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe",
];

export const INDUSTRY_SECTORS = [
  "Banking & Financial Services",
  "Insurance",
  "FinTech",
  "Healthcare",
  "Pharmaceuticals",
  "Manufacturing",
  "IT & Software",
  "Telecommunications",
  "Energy & Utilities",
  "Retail & E-commerce",
  "Government/Public Sector",
  "Education",
  "Logistics & Transportation",
  "Real Estate",
  "Other",
];

export const ORGANISATION_TYPES = [
  "Private Limited Company",
  "Public Limited Company",
  "LLP",
  "Partnership",
  "Sole Proprietorship",
  "Government Entity",
  "Non-Profit Organization",
  "Subsidiary",
  "Holding Company",
  "Startup",
];

export const TIMEZONES = [
  "UTC-12:00 (Baker Island)",
  "UTC-11:00 (Pago Pago)",
  "UTC-10:00 (HST - Hawaii)",
  "UTC-09:30 (Marquesas Islands)",
  "UTC-09:00 (AKST - Alaska)",
  "UTC-08:00 (PST - Pacific)",
  "UTC-07:00 (MST - Mountain)",
  "UTC-06:00 (CST - Central)",
  "UTC-05:00 (EST - Eastern)",
  "UTC-04:00 (AST - Atlantic)",
  "UTC-03:30 (NST - Newfoundland)",
  "UTC-03:00 (ART - Argentina)",
  "UTC-02:00 (South Georgia)",
  "UTC-01:00 (Azores)",
  "UTC+00:00 (GMT - Greenwich)",
  "UTC+01:00 (CET - Central European)",
  "UTC+02:00 (EET - Eastern European)",
  "UTC+03:00 (MSK - Moscow)",
  "UTC+03:30 (IRST - Iran)",
  "UTC+04:00 (GST - Gulf)",
  "UTC+04:30 (AFT - Afghanistan)",
  "UTC+05:00 (PKT - Pakistan)",
  "UTC+05:30 (IST - India)",
  "UTC+05:45 (NPT - Nepal)",
  "UTC+06:00 (BST - Bangladesh)",
  "UTC+06:30 (MMT - Myanmar)",
  "UTC+07:00 (ICT - Indochina)",
  "UTC+08:00 (CST - China/Singapore)",
  "UTC+08:45 (ACWST - Australia CW)",
  "UTC+09:00 (JST - Japan/Korea)",
  "UTC+09:30 (ACST - Australia Central)",
  "UTC+10:00 (AEST - Australia Eastern)",
  "UTC+10:30 (LHST - Lord Howe)",
  "UTC+11:00 (SBT - Solomon Islands)",
  "UTC+12:00 (NZST - New Zealand)",
  "UTC+12:45 (Chatham Islands)",
  "UTC+13:00 (TOT - Tonga)",
  "UTC+14:00 (LINT - Line Islands)",
];

export const LANGUAGES = [
  "Afrikaans", "Albanian", "Amharic", "Arabic", "Armenian", "Azerbaijani", "Basque", "Belarusian",
  "Bengali", "Bosnian", "Bulgarian", "Burmese", "Catalan", "Cebuano", "Chinese (Simplified)",
  "Chinese (Traditional)", "Croatian", "Czech", "Danish", "Dutch", "English", "Esperanto", "Estonian",
  "Filipino", "Finnish", "French", "Galician", "Georgian", "German", "Greek", "Gujarati", "Haitian Creole",
  "Hausa", "Hebrew", "Hindi", "Hungarian", "Icelandic", "Igbo", "Indonesian", "Irish", "Italian",
  "Japanese", "Javanese", "Kannada", "Kazakh", "Khmer", "Kinyarwanda", "Korean", "Kurdish", "Kyrgyz",
  "Lao", "Latin", "Latvian", "Lithuanian", "Luxembourgish", "Macedonian", "Malagasy", "Malay",
  "Malayalam", "Maltese", "Maori", "Marathi", "Mongolian", "Nepali", "Norwegian", "Odia", "Pashto",
  "Persian", "Polish", "Portuguese", "Punjabi", "Romanian", "Russian", "Samoan", "Scottish Gaelic",
  "Serbian", "Sesotho", "Shona", "Sindhi", "Sinhala", "Slovak", "Slovenian", "Somali", "Spanish",
  "Sundanese", "Swahili", "Swedish", "Tajik", "Tamil", "Tatar", "Telugu", "Thai", "Turkish", "Turkmen",
  "Ukrainian", "Urdu", "Uyghur", "Uzbek", "Vietnamese", "Welsh", "Xhosa", "Yiddish", "Yoruba", "Zulu",
];

export const BUSINESS_MODELS = [
  "B2B",
  "B2C",
  "B2B2C",
  "SaaS",
  "PaaS",
  "On-Premise",
  "Hybrid",
  "Marketplace",
  "Subscription-based",
  "Project-based",
];

export const TARGET_AUDIENCES = [
  "Enterprises",
  "SMEs",
  "Startups",
  "Government Agencies",
  "Internal Employees",
  "Compliance Teams",
  "Risk Managers",
  "Auditors",
  "Customers",
  "Partners",
];

export const TECHNOLOGIES = [
  "Cloud (AWS)",
  "Cloud (Azure)",
  "Cloud (GCP)",
  "On-Prem Infrastructure",
  "AI/ML",
  "RPA",
  "Blockchain",
  "Data Analytics",
  "ERP Integration",
  "API-based Architecture",
  "Microservices Architecture",
  "Legacy Systems",
];
