import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { withAuth } from '@/lib/api-auth';

interface RouteContext {
  params: Promise<{ id: string }>;
}

// Generate AI review text based on evidence requests
function generateAIReview(evidenceRequests: Array<{
  id: string;
  title: string;
  description: string | null;
  status: string;
  dueDate: Date | null;
  auditeeName: string | null;
  sampleSize: string | null;
  attachments: Array<{
    id: string;
    fileName: string;
    fileType: string | null;
  }>;
}>): string {
  if (evidenceRequests.length === 0) {
    return 'No evidence requests selected for review.';
  }

  const totalRequests = evidenceRequests.length;
  const pendingCount = evidenceRequests.filter(er => er.status === 'Pending').length;
  const submittedCount = evidenceRequests.filter(er => er.status === 'Submitted').length;
  const reviewedCount = evidenceRequests.filter(er => er.status === 'Reviewed').length;
  const totalAttachments = evidenceRequests.reduce((acc, er) => acc + er.attachments.length, 0);
  const overdueCount = evidenceRequests.filter(er =>
    er.dueDate && new Date(er.dueDate) < new Date() && er.status !== 'Reviewed'
  ).length;

  let review = `AI REVIEW SUMMARY
================

OVERVIEW
--------
Total Evidence Requests Reviewed: ${totalRequests}
Total Supporting Documents: ${totalAttachments}

STATUS BREAKDOWN
----------------
- Pending: ${pendingCount} request(s)
- Submitted: ${submittedCount} request(s)
- Reviewed: ${reviewedCount} request(s)
${overdueCount > 0 ? `- Overdue: ${overdueCount} request(s) - ATTENTION REQUIRED` : ''}

DETAILED ANALYSIS
-----------------
`;

  evidenceRequests.forEach((er, index) => {
    const isOverdue = er.dueDate && new Date(er.dueDate) < new Date() && er.status !== 'Reviewed';
    const dueDateStr = er.dueDate ? new Date(er.dueDate).toLocaleDateString() : 'Not specified';

    review += `
${index + 1}. ${er.title}
   Status: ${er.status}${isOverdue ? ' (OVERDUE)' : ''}
   Due Date: ${dueDateStr}
   Assigned To: ${er.auditeeName || 'Not assigned'}
   Description: ${er.description || 'No description provided'}
   Attachments: ${er.attachments.length} file(s)
   ${er.attachments.length > 0 ? `   Files: ${er.attachments.map(a => a.fileName).join(', ')}` : ''}
`;
  });

  review += `
RECOMMENDATIONS
---------------
`;

  if (pendingCount > 0) {
    review += `1. Follow up on ${pendingCount} pending evidence request(s) to ensure timely submission.\n`;
  }

  if (overdueCount > 0) {
    review += `2. PRIORITY: Address ${overdueCount} overdue evidence request(s) immediately.\n`;
  }

  if (evidenceRequests.some(er => er.attachments.length === 0 && er.status !== 'Pending')) {
    review += `3. Some submitted requests lack supporting documentation. Request additional evidence.\n`;
  }

  if (reviewedCount === totalRequests) {
    review += `All evidence requests have been reviewed. Audit documentation is complete.\n`;
  }

  review += `
CONCLUSION
----------
Based on the review of ${totalRequests} evidence request(s), the audit fieldwork ${
    reviewedCount === totalRequests ? 'documentation is complete and ready for final review.' :
    overdueCount > 0 ? 'requires immediate attention to address overdue items before proceeding.' :
    pendingCount > totalRequests / 2 ? 'is in early stages. Continue follow-up with auditees.' :
    'is progressing well. Continue monitoring outstanding items.'
}

---
Generated by VerifAI Audit Assistant
Date: ${new Date().toLocaleString()}
`;

  return review;
}

// POST /api/internal-audit/fieldwork/[id]/ai-review - Generate AI review for selected evidence requests
export const POST = withAuth(
  async (req: NextRequest, context: RouteContext) => {
    try {
      const { id: engagementId } = await context.params;
      const body = await req.json();
      const { evidenceRequestIds } = body;

      if (!evidenceRequestIds || !Array.isArray(evidenceRequestIds) || evidenceRequestIds.length === 0) {
        return NextResponse.json(
          { error: 'No evidence request IDs provided' },
          { status: 400 }
        );
      }

      // Verify engagement exists
      const engagement = await prisma.auditEngagement.findUnique({
        where: { id: engagementId },
      });

      if (!engagement) {
        return NextResponse.json(
          { error: 'Engagement not found' },
          { status: 404 }
        );
      }

      // Fetch the selected evidence requests with attachments
      const evidenceRequests = await prisma.fieldworkEvidenceRequest.findMany({
        where: {
          id: { in: evidenceRequestIds },
          engagementId: engagementId,
        },
        include: {
          attachments: {
            select: {
              id: true,
              fileName: true,
              fileType: true,
            },
          },
        },
        orderBy: { createdAt: 'asc' },
      });

      if (evidenceRequests.length === 0) {
        return NextResponse.json(
          { error: 'No valid evidence requests found' },
          { status: 404 }
        );
      }

      // Generate AI review
      const review = generateAIReview(evidenceRequests);

      return NextResponse.json({
        review,
        reviewedCount: evidenceRequests.length,
        generatedAt: new Date().toISOString(),
      });
    } catch (error) {
      console.error('Error generating AI review:', error);
      return NextResponse.json(
        { error: 'Failed to generate AI review' },
        { status: 500 }
      );
    }
  },
  { resource: 'audit.fieldwork', action: 'view' }
);
