/**
 * Data Query Engine — NLP-to-SQL pipeline for chatbot data queries (Phase 2B)
 *
 * Converts natural language questions into structured query specs using LLM,
 * then executes them safely via Prisma with mandatory tenant isolation.
 *
 * Security:
 * - Never uses raw SQL — all queries go through Prisma ORM
 * - Mandatory customerAccountId filter on every query
 * - Whitelist of queryable models and fields
 * - Role-based model access control
 * - Result row limit (max 50)
 */

import OpenAI from "openai";
import prisma from "@/lib/prisma";
import {
  QUERYABLE_MODELS,
  buildSchemaPrompt,
  getAccessibleModelNames,
  type ModelMeta,
} from "./schema-metadata";
import { getAMVendorIds, type AuthenticatedRequest } from "@/lib/api-auth";

type ChatSession = AuthenticatedRequest["user"];

// ==================== CONFIGURATION ====================

const DATA_QUERY_MODEL = "gpt-4o-mini";
const MAX_RESULT_ROWS = 50;

let openaiClient: OpenAI | null = null;

function getOpenAI(): OpenAI {
  if (!openaiClient) {
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) throw new Error("OPENAI_API_KEY is not configured");
    openaiClient = new OpenAI({ apiKey });
  }
  return openaiClient;
}

// ==================== TYPES ====================

/** Structured query spec generated by LLM — NOT raw SQL */
export interface QuerySpec {
  /** Prisma model name to query */
  model: string;
  /** Type of operation */
  operation: "count" | "list" | "aggregate" | "group";
  /** Filters to apply (field → value) */
  filters: Record<string, unknown>;
  /** For group operations: field to group by */
  groupBy?: string;
  /** For aggregate: field and function */
  aggregate?: { field: string; function: "sum" | "avg" | "min" | "max" };
  /** For list: fields to select */
  select?: string[];
  /** Sort field and direction */
  orderBy?: { field: string; direction: "asc" | "desc" };
  /** Limit rows */
  limit?: number;
}

export interface DataQueryResult {
  content: string;
  data?: unknown;
  querySpec?: QuerySpec;
  tokensUsed: number;
  confidence: "high" | "medium" | "low";
}

// ==================== LLM QUERY SPEC GENERATION ====================

const SYSTEM_PROMPT = `You are a data query translator for a GRC (Governance, Risk, and Compliance) application. Your job is to convert natural language questions about data into a structured JSON query specification.

RULES (NEVER VIOLATE):
1. Output ONLY a valid JSON object — no explanation, no markdown, no extra text.
2. ONLY use models and fields from the schema provided below.
3. NEVER fabricate field names or model names.
4. For department/category/framework filters: use the "relation_name" format (e.g. departmentId with value being the department name — the system will resolve it).
5. String filter values should be case-insensitive partial matches unless they match known enum values exactly.
6. For date filters, use ISO format and relative terms: "today", "this_month", "this_year", "overdue" (before today).
7. If the question cannot be answered from the available schema, set "model" to "UNSUPPORTED".
8. For "which department has the most X" questions, use operation "group" with groupBy "departmentId" — NOT aggregate.
9. The "aggregate" operation is ONLY for numeric calculations (sum, avg, min, max) on aggregatable number fields like riskScore, value, plannedHours.
10. There are TWO risk models: "Risk" (GRC Risk Management module) and "InternalAuditRisk" (Internal Audit module). If the user just says "risks" without specifying audit context, default to "Risk" — the system will auto-redirect to the audit risk model if the user lacks GRC access.
11. IMPORTANT: The conversation history (prior messages) may be included. If the user uses pronouns or references like "this", "it", "that control", "the same one", "of this", resolve them from the conversation context. For example, if the previous message asked about "Consent Management System Implementation" control and the user now asks "what is its functional grouping", generate a query for the Control model filtering by name "Consent Management System Implementation" and selecting "functionalGrouping".

OUTPUT FORMAT (JSON only):
{
  "model": "Risk",
  "operation": "count" | "list" | "aggregate" | "group",
  "filters": { "status": "Open", "departmentId": "IT Department" },
  "groupBy": "status",
  "aggregate": { "field": "riskScore", "function": "avg" },
  "select": ["riskId", "name", "status", "riskRating"],
  "orderBy": { "field": "riskScore", "direction": "desc" },
  "limit": 10
}

Only include fields that are relevant. Omit optional fields if not needed.`;

// ==================== CONVERSATION HISTORY TYPE ====================

interface ConversationMessage {
  role: "user" | "bot";
  content: string;
}

/**
 * Use LLM to convert natural language query to structured QuerySpec.
 * Includes conversation history so follow-ups like "show me its status"
 * can resolve "it" to the entity from the previous turn.
 */
async function generateQuerySpec(
  query: string,
  userRoles: string[],
  conversationHistory: ConversationMessage[] = []
): Promise<{ spec: QuerySpec; tokensUsed: number }> {
  const client = getOpenAI();
  const schemaDesc = buildSchemaPrompt(userRoles);

  // Build messages with conversation context
  const messages: { role: "system" | "user" | "assistant"; content: string }[] = [
    { role: "system", content: SYSTEM_PROMPT },
  ];

  // Include recent conversation so LLM can resolve references like "this", "it", "that control"
  const recentHistory = conversationHistory.slice(-4);
  for (const msg of recentHistory) {
    messages.push({
      role: msg.role === "user" ? "user" : "assistant",
      content: msg.content,
    });
  }

  // Current query with schema
  messages.push({
    role: "user",
    content: `AVAILABLE SCHEMA:\n\n${schemaDesc}\n\n---\n\nUser question: ${query}\n\nGenerate the JSON query specification:`,
  });

  const response = await client.chat.completions.create({
    model: DATA_QUERY_MODEL,
    messages,
    max_completion_tokens: 500,
    temperature: 0.1,
    response_format: { type: "json_object" },
  });

  const raw = response.choices[0]?.message?.content || "{}";
  const tokensUsed = response.usage?.total_tokens || 0;

  try {
    const parsed = JSON.parse(raw) as QuerySpec;
    return { spec: parsed, tokensUsed };
  } catch {
    return {
      spec: { model: "UNSUPPORTED", operation: "count", filters: {} },
      tokensUsed,
    };
  }
}

// ==================== MODEL FALLBACK MAP ====================

/**
 * When a user doesn't have access to a model, check if there's a
 * module-specific equivalent they DO have access to.
 * e.g. GRC "Risk" → Internal Audit "InternalAuditRisk"
 */
interface ModelFallback {
  targetModel: string;
  /** Maps source field names to target field names (only for fields that differ) */
  fieldMap?: Record<string, string>;
}

const MODEL_FALLBACK_MAP: Record<string, ModelFallback> = {
  // Audit users asking about "risks" should get Internal Audit Risk data
  Risk: {
    targetModel: "InternalAuditRisk",
    fieldMap: {
      name: "riskName",
      riskRating: "riskLevel",
      riskScore: "inherentScore",
      likelihood: "inherentLikelihood",
      impact: "inherentImpact",
    },
  },
};

/**
 * Remap fields in a QuerySpec when falling back to an alternative model.
 */
function remapFields(spec: QuerySpec, fieldMap: Record<string, string>): void {
  // Remap filters
  if (spec.filters) {
    const newFilters: Record<string, unknown> = {};
    for (const [key, value] of Object.entries(spec.filters)) {
      newFilters[fieldMap[key] || key] = value;
    }
    spec.filters = newFilters;
  }

  // Remap select
  if (spec.select) {
    spec.select = spec.select.map((f) => fieldMap[f] || f);
  }

  // Remap groupBy
  if (spec.groupBy && fieldMap[spec.groupBy]) {
    spec.groupBy = fieldMap[spec.groupBy];
  }

  // Remap orderBy
  if (spec.orderBy && fieldMap[spec.orderBy.field]) {
    spec.orderBy.field = fieldMap[spec.orderBy.field];
  }

  // Remap aggregate
  if (spec.aggregate && fieldMap[spec.aggregate.field]) {
    spec.aggregate.field = fieldMap[spec.aggregate.field];
  }
}

// ==================== QUERY VALIDATION ====================

/**
 * Validate that the query spec only uses whitelisted models and fields.
 */
function validateQuerySpec(
  spec: QuerySpec,
  userRoles: string[]
): { valid: boolean; error?: string; modelMeta?: ModelMeta } {
  if (spec.model === "UNSUPPORTED") {
    return { valid: false, error: "This type of data query is not supported yet." };
  }

  // Resolve model name: LLM might say "Vendor" instead of "TPRMVendor"
  let modelMeta = QUERYABLE_MODELS.find((m) => m.prismaModel === spec.model);
  if (!modelMeta) {
    // Try matching by display name or alias
    modelMeta = QUERYABLE_MODELS.find(
      (m) =>
        m.displayName.toLowerCase() === spec.model.toLowerCase() ||
        m.aliases.some((a) => a.toLowerCase() === spec.model.toLowerCase())
    );
    if (modelMeta) {
      spec.model = modelMeta.prismaModel; // Fix the model name
    }
  }

  if (!modelMeta) {
    return { valid: false, error: "Unknown data model." };
  }

  // Check role access
  const accessibleModels = getAccessibleModelNames(userRoles);
  if (!accessibleModels.includes(spec.model)) {
    // Smart fallback: If user asked about "Risk" but only has audit access,
    // redirect to InternalAuditRisk (the audit module's risk register)
    const fallbackModel = MODEL_FALLBACK_MAP[spec.model];
    if (fallbackModel && accessibleModels.includes(fallbackModel.targetModel)) {
      const altMeta = QUERYABLE_MODELS.find((m) => m.prismaModel === fallbackModel.targetModel);
      if (altMeta) {
        spec.model = fallbackModel.targetModel;
        // Remap any filters/select/groupBy/orderBy fields that differ between models
        if (fallbackModel.fieldMap) {
          remapFields(spec, fallbackModel.fieldMap);
        }
        modelMeta = altMeta;
        // Continue validation with the fallback model
      }
    } else {
      return {
        valid: false,
        error: `I'm sorry, but ${modelMeta.displayName} data is outside your current role's access permissions. Your role (${userRoles.join(", ")}) does not have access to the ${modelMeta.displayName} module. Please contact your administrator if you need access to this information.`,
      };
    }
  }
  // Validate operation
  const validOps = ["count", "list", "aggregate", "group"];
  if (!validOps.includes(spec.operation)) {
    return { valid: false, error: "Unsupported query operation." };
  }

  // Validate filter fields
  const validFields = new Set(modelMeta.fields.map((f) => f.name));
  for (const key of Object.keys(spec.filters || {})) {
    if (!validFields.has(key)) {
      return { valid: false, error: `Unknown filter field: ${key}` };
    }
  }

  // Validate select fields
  if (spec.select) {
    for (const field of spec.select) {
      if (!validFields.has(field)) {
        return { valid: false, error: `Unknown select field: ${field}` };
      }
    }
  }

  // Validate groupBy field
  if (spec.groupBy && !validFields.has(spec.groupBy)) {
    return { valid: false, error: `Unknown groupBy field: ${spec.groupBy}` };
  }

  // Validate aggregate field
  if (spec.aggregate) {
    if (!validFields.has(spec.aggregate.field)) {
      return { valid: false, error: `Unknown aggregate field: ${spec.aggregate.field}` };
    }
    const fieldMeta = modelMeta.fields.find((f) => f.name === spec.aggregate!.field);
    if (fieldMeta && !fieldMeta.aggregatable) {
      return { valid: false, error: `Field ${spec.aggregate.field} cannot be aggregated.` };
    }
  }

  return { valid: true, modelMeta };
}

// ==================== QUERY EXECUTION ====================

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 * Search DynamicTranslation table to find record IDs matching a translated text.
 * This handles the case where data is stored in one language (e.g. Arabic) but
 * the user asks in another language (e.g. English) using the translated name they see in the UI.
 */
async function findRecordIdsByTranslation(
  modelName: string,
  fieldName: string,
  searchText: string,
  customerAccountId: string
): Promise<string[]> {
  try {
    const translations = await prisma.dynamicTranslation.findMany({
      where: {
        customerAccountId,
        modelName,
        fieldName,
        translatedText: { contains: searchText, mode: "insensitive" },
      },
      select: { recordId: true },
    });
    return translations.map((t) => t.recordId);
  } catch {
    return [];
  }
}

/**
 * Resolve relation filters (e.g. departmentId: "IT Department" → actual ID).
 */
async function resolveRelationFilters(
  filters: Record<string, unknown>,
  modelMeta: ModelMeta,
  customerAccountId: string
): Promise<Record<string, unknown>> {
  const resolved: Record<string, unknown> = {};

  for (const [key, value] of Object.entries(filters)) {
    const fieldMeta = modelMeta.fields.find((f) => f.name === key);

    if (fieldMeta?.relation && typeof value === "string") {
      // Resolve the relation name to an ID
      const relationModel = fieldMeta.relation.model;
      const displayField = fieldMeta.relation.displayField;

      try {
        // First try direct match
        let record = await (prisma as any)[lowerFirst(relationModel)].findFirst({
          where: {
            customerAccountId,
            [displayField]: { contains: value, mode: "insensitive" },
          },
          select: { id: true, [displayField]: true },
        });

        // If not found, try via DynamicTranslation (data may be in another language)
        if (!record) {
          const translatedIds = await findRecordIdsByTranslation(
            relationModel, displayField, value, customerAccountId
          );
          if (translatedIds.length > 0) {
            record = await (prisma as any)[lowerFirst(relationModel)].findFirst({
              where: { id: { in: translatedIds } },
              select: { id: true, [displayField]: true },
            });
          }
        }

        if (record) {
          resolved[key] = record.id;
        }
        // If not found, skip this filter silently
      } catch {
        // Skip unresolvable relations
      }
    } else {
      resolved[key] = value;
    }
  }

  return resolved;
}

/**
 * Build Prisma where clause from resolved filters.
 */
function buildWhereClause(
  filters: Record<string, unknown>,
  modelMeta: ModelMeta,
  customerAccountId: string
): Record<string, unknown> {
  const where: Record<string, unknown> = {
    customerAccountId,
  };

  for (const [key, value] of Object.entries(filters)) {
    const fieldMeta = modelMeta.fields.find((f) => f.name === key);
    if (!fieldMeta) continue;

    if (fieldMeta.type === "string" && typeof value === "string") {
      // Check if value matches a known enum exactly
      if (fieldMeta.values?.some((v) => v.toLowerCase() === value.toLowerCase())) {
        const exactMatch = fieldMeta.values.find(
          (v) => v.toLowerCase() === value.toLowerCase()
        );
        where[key] = exactMatch;
      } else if (fieldMeta.relation) {
        // Already resolved to ID
        where[key] = value;
      } else {
        // Partial match for free-text fields
        where[key] = { contains: value, mode: "insensitive" };
      }
    } else if (fieldMeta.type === "number" && typeof value === "number") {
      where[key] = value;
    } else if (fieldMeta.type === "boolean" && typeof value === "boolean") {
      where[key] = value;
    } else if (fieldMeta.type === "date" && typeof value === "string") {
      // Handle relative date terms
      const now = new Date();
      if (value === "overdue") {
        where[key] = { lt: now };
      } else if (value === "today") {
        const startOfDay = new Date(now.getFullYear(), now.getMonth(), now.getDate());
        const endOfDay = new Date(startOfDay.getTime() + 24 * 60 * 60 * 1000);
        where[key] = { gte: startOfDay, lt: endOfDay };
      } else if (value === "this_month") {
        const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);
        const endOfMonth = new Date(now.getFullYear(), now.getMonth() + 1, 1);
        where[key] = { gte: startOfMonth, lt: endOfMonth };
      } else if (value === "this_year") {
        const startOfYear = new Date(now.getFullYear(), 0, 1);
        const endOfYear = new Date(now.getFullYear() + 1, 0, 1);
        where[key] = { gte: startOfYear, lt: endOfYear };
      } else {
        // Try ISO date
        const date = new Date(value);
        if (!isNaN(date.getTime())) {
          where[key] = { gte: date };
        }
      }
    }
  }

  return where;
}

// ==================== ROLE-BASED SCOPE (per model) ====================

/**
 * Offboard assessment statuses each role is allowed to see.
 * Mirrors `/api/tprm/offboard-assessments` role-based status filtering.
 */
const OFFBOARD_STATUS_BY_ROLE: Record<string, string[]> = {
  RelationshipManager: ["Offboard_Approve_RM", "Offboard_Completed"],
  BusinessOwner: ["Offboard_Approve_BO", "Offboard_Completed"],
  TPRMAssessor: ["Offboard_Approve_Assessor", "Offboard_Completed"],
  TPRMApprover: ["Offboard_Approve_Assessor", "Offboard_Completed"],
  AccountManager: ["Offboard_In_Progress", "Offboard_Awaiting_Response"],
  TPRMSME: ["Offboard_In_Progress", "Offboard_Awaiting_Response"],
};

/** Roles that see every assessment in the tenant without extra filters. */
const ASSESSMENT_FULL_TENANT_ROLES = new Set([
  "GRCAdministrator",
  "TPRMAdmin",
  "TPRMAuditor",
]);

/** Roles that see all regular assessments in the tenant + their offboard queue. */
const ASSESSMENT_BROAD_ROLES = new Set([
  "RelationshipManager",
  "BusinessOwner",
  "TPRMAssessor",
  "TPRMApprover",
]);

/** Roles whose assessment access is limited to the vendors assigned to them. */
const ASSESSMENT_AM_ROLES = new Set(["AccountManager", "TPRMSME"]);

/** Roles that only see Assessment Factory-type assessments. */
const ASSESSMENT_FACTORY_ONLY_ROLES = new Set(["FactoryAdmin", "FactoryAssessor"]);

/**
 * Pure role-scope computer for TPRMAssessment — no DB access.
 * Returns the WHERE fragment to AND with the tenant filter, or a sentinel
 * { __deny: true } to force an impossible match (access denied).
 * Exposed for unit testing.
 */
export function buildAssessmentRoleScope(
  roles: string[],
  amVendorIds: string[]
): Record<string, unknown> | { __deny: true } | null {
  // Tier 1: full-tenant read — no extra scoping
  if (roles.some((r) => ASSESSMENT_FULL_TENANT_ROLES.has(r))) return null;

  const scopeClauses: Record<string, unknown>[] = [];

  // Tier 2: broad role (RM/BO/Assessor/Approver) — regular + role's offboard statuses
  if (roles.some((r) => ASSESSMENT_BROAD_ROLES.has(r))) {
    const offboardStatuses = Array.from(
      new Set(roles.flatMap((r) => OFFBOARD_STATUS_BY_ROLE[r] || []))
    );
    scopeClauses.push({
      OR: [
        { assessmentType: { not: "Offboard Assessment" } },
        offboardStatuses.length > 0
          ? {
              AND: [
                { assessmentType: "Offboard Assessment" },
                { status: { in: offboardStatuses } },
              ],
            }
          : { id: "__never__" },
      ],
    });
  }

  // Tier 3: AM/SME — vendor-scoped
  if (roles.some((r) => ASSESSMENT_AM_ROLES.has(r))) {
    const amOffboardStatuses = OFFBOARD_STATUS_BY_ROLE.AccountManager;
    scopeClauses.push({
      AND: [
        { vendorId: { in: amVendorIds.length > 0 ? amVendorIds : ["__none__"] } },
        {
          OR: [
            { assessmentType: { not: "Offboard Assessment" } },
            {
              AND: [
                { assessmentType: "Offboard Assessment" },
                { status: { in: amOffboardStatuses } },
              ],
            },
          ],
        },
      ],
    });
  }

  // Tier 4: Factory-only — restrict to Assessment Factory type (only if no broader tier applied)
  if (
    scopeClauses.length === 0 &&
    roles.some((r) => ASSESSMENT_FACTORY_ONLY_ROLES.has(r))
  ) {
    scopeClauses.push({ assessmentType: "Assessment Factory" });
  }

  if (scopeClauses.length === 0) return { __deny: true };
  return scopeClauses.length === 1 ? scopeClauses[0] : { OR: scopeClauses };
}

/**
 * Augment the WHERE clause with model-specific role scoping.
 * Currently only TPRMAssessment requires scoping beyond customerAccountId.
 */
async function applyRoleScope(
  where: Record<string, unknown>,
  modelMeta: ModelMeta,
  session: ChatSession | undefined,
  customerAccountId: string
): Promise<void> {
  if (modelMeta.prismaModel !== "TPRMAssessment") return;
  if (!session) return;

  const roles = session.roles || [];
  const needsAmLookup = roles.some((r) => ASSESSMENT_AM_ROLES.has(r));
  const amVendorIds = needsAmLookup
    ? await getAMVendorIds(session, customerAccountId)
    : [];

  const scope = buildAssessmentRoleScope(roles, amVendorIds);
  if (scope === null) return;

  if ("__deny" in scope) {
    where.id = "__denied__";
    return;
  }

  const existingAnd = Array.isArray(where.AND) ? (where.AND as unknown[]) : [];
  where.AND = [...existingAnd, scope];
}

/**
 * Execute the validated query spec via Prisma.
 */
async function executeQuery(
  spec: QuerySpec,
  modelMeta: ModelMeta,
  customerAccountId: string,
  session?: ChatSession
): Promise<unknown> {
  const prismaModel = (prisma as any)[lowerFirst(spec.model)];
  if (!prismaModel) throw new Error(`Model ${spec.model} not available`);

  // Split "me"/"myself"/"i" on user-relation fields from the rest, so they
  // aren't mis-looked-up against User.fullName during relation resolution.
  const rawFilters: Record<string, unknown> = { ...(spec.filters || {}) };
  const meOverrides: Record<string, string> = {};
  if (session?.id) {
    for (const [k, v] of Object.entries(rawFilters)) {
      if (typeof v !== "string") continue;
      const normalized = v.trim().toLowerCase();
      if (normalized !== "me" && normalized !== "myself" && normalized !== "i") continue;
      const fieldMeta = modelMeta.fields.find((f) => f.name === k);
      if (fieldMeta?.relation?.model === "User") {
        meOverrides[k] = session.id;
        delete rawFilters[k];
      }
    }
  }

  // Resolve relation filters first
  const resolvedFilters = await resolveRelationFilters(
    rawFilters,
    modelMeta,
    customerAccountId
  );

  // Re-apply the "me" resolutions using the current user id
  Object.assign(resolvedFilters, meOverrides);

  // Build where clause, then enhance with translation-aware search
  const where = buildWhereClause(resolvedFilters, modelMeta, customerAccountId);

  // Apply model-specific role-based scoping (e.g. TPRM assessment role scopes)
  await applyRoleScope(where, modelMeta, session, customerAccountId);

  // Translation-aware: for text filters on name/description fields, also search
  // DynamicTranslation table in case the data is stored in a different language
  // than what the user typed (e.g. user types English, data stored in Arabic)
  for (const [key, value] of Object.entries(resolvedFilters)) {
    if (typeof value !== "string") continue;
    const fieldMeta = modelMeta.fields.find((f) => f.name === key);
    if (!fieldMeta || fieldMeta.type !== "string" || fieldMeta.relation || fieldMeta.values) continue;

    // Search translations for this field
    const translatedIds = await findRecordIdsByTranslation(
      spec.model, key, value, customerAccountId
    );

    if (translatedIds.length > 0) {
      // Use OR: match by original text OR by translated record IDs
      const originalFilter = where[key];
      delete where[key];
      where.OR = [
        { [key]: originalFilter },
        { id: { in: translatedIds } },
      ];
    }
  }

  const limit = Math.min(spec.limit || MAX_RESULT_ROWS, MAX_RESULT_ROWS);

  switch (spec.operation) {
    case "count":
      return prismaModel.count({ where });

    case "list": {
      // Build select object with safe fields only
      const selectFields: Record<string, unknown> = {};
      const fieldsToSelect = spec.select || [
        modelMeta.codeField,
        modelMeta.nameField,
        "status",
      ].filter(Boolean);

      for (const f of fieldsToSelect) {
        if (!f) continue;
        const fieldMeta = modelMeta.fields.find((fm) => fm.name === f);
        if (!fieldMeta) continue;

        if (fieldMeta.relation) {
          // Include the relation for display — use explicit relationField if specified
          selectFields[f] = true;
          const relField = fieldMeta.relation.relationField || lowerFirst(fieldMeta.relation.model);
          selectFields[relField] = {
            select: { [fieldMeta.relation.displayField]: true },
          };
        } else {
          selectFields[f] = true;
        }
      }

      const orderBy = spec.orderBy
        ? { [spec.orderBy.field]: spec.orderBy.direction }
        : { createdAt: "desc" as const };

      return prismaModel.findMany({
        where,
        select: Object.keys(selectFields).length > 0 ? selectFields : undefined,
        orderBy,
        take: limit,
      });
    }

    case "group": {
      if (!spec.groupBy) throw new Error("groupBy field required for group operation");

      const fieldMeta = modelMeta.fields.find((f) => f.name === spec.groupBy);

      if (fieldMeta?.relation) {
        // For relation fields, we need to fetch and group manually
        const relField = fieldMeta.relation.relationField || lowerFirst(fieldMeta.relation.model);
        const records = await prismaModel.findMany({
          where,
          select: {
            [spec.groupBy]: true,
            [relField]: {
              select: { [fieldMeta.relation.displayField]: true },
            },
          },
        });

        const groups: Record<string, number> = {};
        for (const r of records) {
          const relObj = r[relField] as Record<string, string> | null;
          const label = relObj?.[fieldMeta.relation.displayField] || "Unknown";
          groups[label] = (groups[label] || 0) + 1;
        }

        return Object.entries(groups)
          .map(([name, count]) => ({ [spec.groupBy!]: name, _count: count }))
          .sort((a, b) => b._count - a._count);
      }

      // For non-relation fields, use groupBy
      const grouped = await prismaModel.groupBy({
        by: [spec.groupBy],
        where,
        _count: true,
      });

      // Sort by count descending
      const mapped = grouped.map((g: any) => ({
        [spec.groupBy!]: g[spec.groupBy!],
        _count: g._count,
      }));
      mapped.sort((a: any, b: any) => b._count - a._count);
      return mapped;
    }

    case "aggregate": {
      if (!spec.aggregate) throw new Error("aggregate spec required");

      const aggField = spec.aggregate.field;
      const aggFn = spec.aggregate.function;

      const result = await prismaModel.aggregate({
        where,
        [`_${aggFn}`]: { [aggField]: true },
        _count: true,
      });

      return {
        function: aggFn,
        field: aggField,
        value: result[`_${aggFn}`]?.[aggField],
        totalRecords: result._count,
      };
    }

    default:
      throw new Error(`Unknown operation: ${spec.operation}`);
  }
}

/* eslint-enable @typescript-eslint/no-explicit-any */

// ==================== RESULT FORMATTING ====================

/**
 * Use LLM to format query results into natural language.
 */
async function formatResults(
  query: string,
  spec: QuerySpec,
  data: unknown,
  modelMeta: ModelMeta
): Promise<{ content: string; tokensUsed: number }> {
  const client = getOpenAI();

  // For simple counts, no need for LLM
  if (spec.operation === "count" && typeof data === "number") {
    const filterDesc = Object.entries(spec.filters || {})
      .map(([k, v]) => `${k}: ${v}`)
      .join(", ");
    const content = filterDesc
      ? `There are **${data}** ${modelMeta.displayName.toLowerCase()}(s) matching your criteria (${filterDesc}).`
      : `There are **${data}** ${modelMeta.displayName.toLowerCase()}(s) in total.`;
    return { content, tokensUsed: 0 };
  }

  // For complex results, use LLM to format
  const dataStr = JSON.stringify(data, null, 2).substring(0, 3000);

  const response = await client.chat.completions.create({
    model: DATA_QUERY_MODEL,
    messages: [
      {
        role: "system",
        content: `You are a GRC application assistant. Format the following data query result into a clear, concise natural language response. Use bullet points or tables where appropriate. Keep it under 200 words. Do NOT reveal table names, column names, or technical details. Use friendly, business-oriented language.`,
      },
      {
        role: "user",
        content: `User asked: "${query}"\n\nQuery type: ${spec.operation} on ${modelMeta.displayName}\nResults:\n${dataStr}\n\nFormat this into a helpful response:`,
      },
    ],
    max_completion_tokens: 500,
    temperature: 0.3,
  });

  const content = response.choices[0]?.message?.content || "Here are the results of your query.";
  const tokensUsed = response.usage?.total_tokens || 0;

  return { content, tokensUsed };
}

// ==================== PUBLIC API ====================

/**
 * Process a data query end-to-end:
 * 1. LLM generates structured QuerySpec from natural language
 * 2. Validate the spec against whitelisted schema
 * 3. Execute via Prisma with tenant isolation
 * 4. Format results into natural language
 */
export async function processDataQuery(
  query: string,
  customerAccountId: string,
  userRoles: string[],
  conversationHistory: ConversationMessage[] = [],
  session?: ChatSession
): Promise<DataQueryResult> {
  // Step 1: Generate query spec from natural language (with conversation context)
  const { spec, tokensUsed: specTokens } = await generateQuerySpec(query, userRoles, conversationHistory);

  // Step 2: Validate the spec
  const validation = validateQuerySpec(spec, userRoles);
  if (!validation.valid || !validation.modelMeta) {
    return {
      content: validation.error || "I couldn't understand that data query. Could you rephrase it?",
      confidence: "low",
      tokensUsed: specTokens,
    };
  }

  // Step 3: Execute the query
  let data: unknown;
  try {
    data = await executeQuery(spec, validation.modelMeta, customerAccountId, session);
  } catch (error) {
    console.error("[DataQuery] Execution error:", error);
    console.error("[DataQuery] Failed spec:", JSON.stringify(spec, null, 2));
    return {
      content: "I encountered an error while fetching the data. Please try rephrasing your question or contact the administrator.",
      confidence: "low",
      tokensUsed: specTokens,
    };
  }

  // Step 4: Format results
  const { content, tokensUsed: formatTokens } = await formatResults(
    query,
    spec,
    data,
    validation.modelMeta
  );

  return {
    content,
    data,
    querySpec: spec,
    confidence: "high",
    tokensUsed: specTokens + formatTokens,
  };
}

// ==================== UTILITY ====================

function lowerFirst(str: string): string {
  return str.charAt(0).toLowerCase() + str.slice(1);
}
